// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity 0.8.7;

import "@openzeppelin/contracts/access/AccessControl.sol";

import "../common/FundsManagementAccessControl.sol";

import "../interfaces/IBallBuyOracleCaller.sol";
import "../interfaces/IBallStruct.sol";

contract BallBuyOracle is AccessControl, FundsManagementAccessControl {
    bool public constant IS_BALL_BUY_ORACLE = true;

    bytes32 public constant REQUESTER_ROLE = keccak256("REQUESTER_ROLE");
    bytes32 public constant REPORTER_ROLE = keccak256("REPORTER_ROLE");

    mapping(address => uint256) private _requestIdNonceByAccount;

    mapping(uint256 => bool) private _pendingRequests;

    event RequestedBallBuy(
        uint256 indexed requestId,
        address indexed callerAddress,
        address indexed to,
        uint16 machineServerId,
        uint16 amount,
        uint256 ticketTokenId
    );
    event ReportedBallBuy(
        uint256 indexed requestId,
        address indexed callerAddress,
        address indexed to,
        BallMintData[] ballsMintData,
        uint256 ticketTokenId
    );

    constructor() {
        _setupRole(DEFAULT_ADMIN_ROLE, _msgSender());
    }

    // Emits the event to trigger the oracle
    function requestBallBuy(
        address _to,
        uint16 _machineServerId,
        uint16 _amount,
        uint256 _ticketTokenId
    ) external onlyRole(REQUESTER_ROLE) returns (uint256) {
        _requestIdNonceByAccount[_msgSender()]++;

        uint256 requestId = _getRequestId(_msgSender());

        _pendingRequests[requestId] = true;

        emit RequestedBallBuy(
            requestId,
            _msgSender(),
            _to,
            _machineServerId,
            _amount,
            _ticketTokenId
        );

        return requestId;
    }

    // Calls the oracle caller back with the random zomon generated by the oracle
    function reportBallBuy(
        uint256 _requestId,
        address _callerAddress,
        address _to,
        string calldata _ballTokenURIPrefix,
        BallMintData[] calldata _ballsMintData,
        uint256 _ticketTokenId
    ) external onlyRole(REPORTER_ROLE) {
        require(_pendingRequests[_requestId], "REQUEST_ID_IS_NOT_PENDING");

        delete _pendingRequests[_requestId];

        IBallBuyOracleCaller callerContractInstance = IBallBuyOracleCaller(
            _callerAddress
        );

        require(
            callerContractInstance.IS_BALL_BUY_ORACLE_CALLER(),
            "CALLER_ADDRESS_IS_NOT_A_BALL_BUY_ORACLE_CALLER_CONTRACT_INSTANCE"
        );

        emit ReportedBallBuy(
            _requestId,
            _callerAddress,
            _to,
            _ballsMintData,
            _ticketTokenId
        );

        callerContractInstance.callback(
            _requestId,
            _to,
            _ballTokenURIPrefix,
            _ballsMintData,
            _ticketTokenId
        );
    }

    function _getRequestId(address _sender) private view returns (uint256) {
        return
            uint256(
                keccak256(
                    abi.encodePacked(_sender, _requestIdNonceByAccount[_sender])
                )
            );
    }
}
